// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIbsbwOAM6WEQtiOMD8ebc3dn_gpyL_AA',
    appId: '1:387535856477:web:e5a6056a70e24fb22dfeb4',
    messagingSenderId: '387535856477',
    projectId: 'trace-buddy',
    authDomain: 'trace-buddy.firebaseapp.com',
    storageBucket: 'trace-buddy.appspot.com',
    measurementId: 'G-ZBJ6Q87ZXN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqhc4vbI42UBrZo1EhVyk0xPJuoJ4szjc',
    appId: '1:387535856477:android:950a5cc3c5f788ab2dfeb4',
    messagingSenderId: '387535856477',
    projectId: 'trace-buddy',
    storageBucket: 'trace-buddy.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiUGApIDp-aJ-TEe2doal_gSK4-s6QjxY',
    appId: '1:387535856477:ios:fabda13ca70231f02dfeb4',
    messagingSenderId: '387535856477',
    projectId: 'trace-buddy',
    storageBucket: 'trace-buddy.appspot.com',
    androidClientId: '387535856477-hlkhag8n9c01aori2u6esfn6ne66rtfb.apps.googleusercontent.com',
    iosClientId: '387535856477-v7eivsc7vq932p7pmjjgtstv8t001kof.apps.googleusercontent.com',
    iosBundleId: 'com.example.traceBuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiUGApIDp-aJ-TEe2doal_gSK4-s6QjxY',
    appId: '1:387535856477:ios:fabda13ca70231f02dfeb4',
    messagingSenderId: '387535856477',
    projectId: 'trace-buddy',
    storageBucket: 'trace-buddy.appspot.com',
    androidClientId: '387535856477-hlkhag8n9c01aori2u6esfn6ne66rtfb.apps.googleusercontent.com',
    iosClientId: '387535856477-v7eivsc7vq932p7pmjjgtstv8t001kof.apps.googleusercontent.com',
    iosBundleId: 'com.example.traceBuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIbsbwOAM6WEQtiOMD8ebc3dn_gpyL_AA',
    appId: '1:387535856477:web:15a2cf88a9eb53aa2dfeb4',
    messagingSenderId: '387535856477',
    projectId: 'trace-buddy',
    authDomain: 'trace-buddy.firebaseapp.com',
    storageBucket: 'trace-buddy.appspot.com',
    measurementId: 'G-JMRX4G6YQ9',
  );

}